### ISSUE TITLE
Asynchronous doAction and applyFilter?

### ISSUE THREAD

**Issue by westonruter** [carldanley/WP-JS-Hooks#1]
Given the concern for browser performance and that JavaScript is extensively asynchronous, has you considered having `doAction` and `applyFilter` run asynchronously instead of synchronously like in PHP? If each registered hook handler were executed asynchronously, then if there were handlers that take a relatively long time to finish—either computationally or due to an Ajax requests—then the browser would be less likely to lock up if there are many of filters registered for a hook.

In the WordSesh presentation, I saw that there were `debounceFilter` and `debounceAction` methods to address an issue related to DOM Events. So there could likewise be asynchronous versions, `applyFilterAsync` and `doActionAsync`. Example usage to illustrate what I'm talking about:

``` js
function titleFilter(title, next) {
    if (!next) {
        console.warn('The titleFilter action must be invoked with applyFilterAsync');
        return title;
    }
    setTimeout(function () { // simulate Ajax or some async request
        title = title.toUpperCase();
        next(title);
    }, 1000);
};
addFilter('wordpress.the_title', titleFilter);
// ...
applyFilterAsync( 'wordpress.the_title', 'Untitled', function (title) {
    alert('The filtered title is: ' + title); // The filtered title is UNTITLED
});
```

So each filter function could be passed a parameter (here `next`) which serves as the callback to pass the value along to the next filter function. When there are no filter functions left, `next` would then invoke the 3rd callback arg supplied to `applyFilterAsync`.

**Comment by mgibbs189** [comment]
Closing, this hasn't gotten any love and likely won't.
